### ISSUE TITLE
Knight quest NPCs other than pages fire impossible due to missing quest_chat

### ISSUE THREAD

**Issue by amateurhourrrr** [Chris-plus-alphanumericgibberish/dNAO#1351]
The rest of the peaceful NPCs when walked into to trigger their peaceful dialogue throw:
`"quest_chat: Unknown quest character %s."`

This includes their variants from quaffing gain level potions (e.g. bachelor levelling up from esquire)

**Comment by Chris-plus-alphanumericgibberish** [comment]
Would be fixed by enhancement #1258, but the bug here could also just be fixed without messing with that.

"Work-in-progress" has been difficult to properly describe, due to a harsh character limit for tag descriptions.  Basically it means "talk to Chris before doing work in this area, there's a high likelihood of patches being declined."

**Comment by Chris-plus-alphanumericgibberish** [comment]
Quest-friendly faction was added and used to handle quest dialog like this.
