### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by Wikid-VoR** [Chris-plus-alphanumericgibberish/dNAO#1388]
My game is crashing on ﻿ascension.run, logged in as VOR.  After I filled up 3/4 of the astral plane with acid blobs, the rest of it filled with dungeon ferns.  It crashes when the ferns finally saturate the floorspace.  (1) I hope this is the right place to post the issue.  (2) I hope you can help!

**Comment by RikerW** [comment]
I can't reproduce this on 3.20 - is there anything else to it? Other than the level being filled up and ferns trying to grow? 

To clarify - I believe there were some changes made in the enexto function since 3.18. Currently, it will just message that "the dungeon fern releases a spore" and the spore creation will fail silently.

**Comment by Wikid-VoR** [comment]
Anachrononaut, was nailed to the sky by an Uvuudaum, can't Annul the Lawful high altar. Now waiting above the altar for levitation to wear off, suspect it will be hundreds of turns. Filling the plane with blobs made it a peaceful place to wait out. The U is still there but I teleported it outside the floor space so it's not coming back. TBH it's hard to see how these things could connect to the crash. I can post a screenshot. Thanks!

**Comment by RikerW** [comment]
Found the issue - read.c has a check for `mtmp->mfaction` that can be called with nonexistent `mtmp`, if monster creation failed. This can be seen if you wizmode fill astral and try to generate something with no space left. This should probably be closed, since that line no longer exists in 3.20 or maybe even 3.19 and this bug is fixed.

**Comment by Wikid-VoR** [comment]
Thanks for this.

**Comment by Wikid-VoR** [comment]
PS my apologies for not identifying the version on ascension.run as 3.18.  Your work has been greatly helpful.  I've alerted Kerio at ascension.run to the bug.  Hopefully they can upgrade to 3.19 or 3.20 and hopefully that doesn't break save files.  Thanks again.

**Comment by RikerW** [comment]
No worries. Unfortunately save files from 3.18 are incompatible with anything newer than 3.19 though. After that game, if you want to play on the latest version and can't compile, I believe the EU version of hardfought.org dnethack 3.20 and is pretty good at staying updated. Not sure what other bugs 3.18 has.

**Comment by Wikid-VoR** [comment]
Thanks!
