### ISSUE TITLE
Quest friendlies angered from angering the leader aren't properly redrawn

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#1433]
When the quest leader is angered, it angers all the friendlies on the level as well, but if highlight peaceful is on, they don't necessarily all get redrawn. Also the code can probably cause problems if called with pets, and should probably call setmangry recursively, like for surya deva blades. This would change how the messaging works because currently it prints one message for all the minions, so maybe setmangry should be refactored to be able to be run silently.

https://github.com/Chris-plus-alphanumericgibberish/dNAO/blob/compat-3.20.0/src/mon.c#L6155

**Comment by NeroOneTrueKing** [comment]
Highlights in general are broken -- `newsym()` often doesn't work, because the glyph actually doesn't change, and it's contextual code that is deciding what background colour to give to a glyph. I am very hesitant to mess with the "don't update glyph if it hasn't changed" check, because that sounds like it could turn into a lot of unnecessary reprinting.

Edit: looks like peaceful highlighting does get its own set of glyphs, and my above paragraph does not apply to this case. Bug should be doable.
