### ISSUE TITLE
Cannot phase diagonally inside walls without grease

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#1588]
Phasing in vanilla allows diagonal movements always, but for some reason in dnh if your outerwear isn't greased and you don't have enough spare carry cap, you can't fit through diagonals in the walls despite the fact you are phasing.

**Comment by NeroOneTrueKing** [comment]
This only happens if you're trying to fit through non-phasable walls -- not reproducing any bad behaviour in normal levels:
![image](https://user-images.githubusercontent.com/28197216/124175703-8a38bb00-da73-11eb-854e-6cab8ea57cc7.png)

If the walls are non-phasable, it makes sense that a phasing creature needs to follow the same rules as non-phasing creatures.

**Comment by demogorgon22** [comment]
I missed that this got closed until I got really bored and started reviewing previous dnh issues by me. Xorns don't have this problem, but base form players phasing from artifacts do.

Steps to replicate:
Start a human convict
Wish for the iron spoon of liberation
Invoke it and walk into a patch of stone
Wish for enough rocks to be encumbered
Now you can't move diagonally :(
