### ISSUE TITLE
Goat mom minions created outside of the depths may not always create properly?

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#1593]
I got a deminymph minion from shubby from my goat altar on dlvl 11 of the main dungeons and it is marked as of moloch and doesn't have the goat mom deminymph inventory loadout.

**Comment by demogorgon22** [comment]
Also it spawned asleep cause it is a nymph which feels wrong.

**Comment by NeroOneTrueKing** [comment]
Being marked as "of moloch" -> minor bug, I thought that had fixed already.

Spawning asleep -> minor bug, we just need to set minions awake when summoned.

Giving it the goat mom deminymph inventory -> complex enhancement because when monsters are reused between areas with drastically different kits, only the *location* tells what kit they should use. I think the correct fix would be an implementation of **factions**.

**Comment by Chris-plus-alphanumericgibberish** [comment]
Note: the mfaction field has been freed up again now that templates have their own field, so this is perfectly doable on that front.

Most grudge stuff and at least some monster starting kits should be transitioned over to factions.

The main hold up is needing to handle setting the faction without expanding the state machine stuff. Nero might be able to add a field to makemon via regular expressions, or mkmon_core could be created (in most cases, the faction will be set inside makemon).

**Comment by NeroOneTrueKing** [comment]
I agree, I'm thinking we should have `makemon_full(mptr, x, y, mmflags, template, faction)` and a `makemon_def(mptr, x, y, mmflags)`.

The `def` version just calls `full` with probably `template=0` and `faction=0` (level-dependent modifiers as well, like living creatures typically being made as vitreans on Baalphegor's level). ~~I'm also thinking `mtyp` instead of `ptr` just because if I'm touching all those lines anyways lets get rid of `&mons[PM_FOO]` calls where we can.~~ Edit: looking closer, that would also mean changing all montype functions used for special levels, which looks like too much scopecreep for what will already be like 48 files.

**Comment by NeroOneTrueKing** [comment]
Done the makemon thing, so now the backend exists to actually implement the bugfix for the deminymph getting the wrong loadout.
