### ISSUE TITLE
Wizard mode #setinsight and #setsanity respect veil and no-madness san-cap, maybe they shouldn't

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#1775]
Trying to set my sanity to 20 it ends up at 50. Trying to set insight does nothing. I think this is veil related?

**Comment by NeroOneTrueKing** [comment]
Insight is veil-related, sanity is madness-related.
Your insight is capped at 0 if you haven't pierced the veil.
Your sanity is floored at 50 if you don't have any madnesses (to prevent you from bottoming out your sanity with very little repercussions and then being whammo-d when you pick up your first madness and it's dialed up to 11).

It might be nice for the wizmode functions to offer to break those barriers for you, instead of you doing the triggers manually.
