### ISSUE TITLE
merge #1763 😡 

### ISSUE THREAD

**Issue by RojjaCebolla** [Chris-plus-alphanumericgibberish/dNAO#1875]
thx 🐱

**Comment by Chris-plus-alphanumericgibberish** [comment]
I mentioned this in chat a while ago, but the issue with #1763 is that blaster charge limits are referencing a second ammo type rather than overheating.

However, I'm still on board with incorporating it in some form. For instance, perhaps charging an already-charged blaster might cause it to explode.

**Comment by NeroOneTrueKing** [comment]
PR was closed, closing related issue.
