### ISSUE TITLE
Monster spell ARROW_RAIN can ~~create stacks of unstackable objects and also~~ use some questionable projectiles

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#1884]
https://github.com/Chris-plus-alphanumericgibberish/dNAO/blob/3dfc134f16aff38d51e4716a6a8cb73d5d0708d6/src/mcastu.c#L2621-L2624
The arrow rain spell can reach a case where it uses a random weapon between arrow and worm tooth. It creates a stack of them and then fires them. Some of these items are unstackable, so arguably, a stack of them being created is insane behavior. This includes all of the spears but javelins. Additionally, some of these items might not make sense to be thrown like the set of crow talons or the tecpatl amongst others. 

Currently there is no failure caused by this, it is just a fault where exists the insane behavior of stacked unstackable items as well as something that should probably be audited due to some of the new items added to that range not making sense.

**Comment by NeroOneTrueKing** [comment]
I agree that some weapons shouldn't be valid for that range, but just because they're too interesting.

The stack of unstackable weapons only exists in `OBJ_FREE` and is fired one object at a time by `projectile()`; there will not be a stack of unstackable weapons afterwards:
![image](https://user-images.githubusercontent.com/28197216/158027449-549d28ea-62a3-4c9a-9892-c68fdad8bf1d.png)

**Comment by NeroOneTrueKing** [comment]
welp can't put strikethroughs in the title

**Comment by Chris-plus-alphanumericgibberish** [comment]
lol was wondering what those tildes were :D

**Comment by Chris-plus-alphanumericgibberish** [comment]
a373ac49f5d2ff2598034194b01a284d48d7f8f5

**Comment by Chris-plus-alphanumericgibberish** [comment]
The items used are explicitly listed now, so they can be further adjusted if anything else is considered questionable (or missing)
