### ISSUE TITLE
Game freezes when yuki-onna try to steal from Mina Harker

### ISSUE THREAD

**Issue by baoliejuan** [Chris-plus-alphanumericgibberish/dNAO#1989]
It happens when a monster has both frilly dress and expensive dress on

**Comment by RikerW** [comment]
I just tried to steal both from her and it did not crash, so I'm not sure what the issue was - was a yuki-onna monk bare-handed attacking Mina Harker and I could steal all of her gear fine. Note that a frilly dress is a shirt-class item, "victorian underwear", and the expensive dress is the armor-class item "gentlewoman's dress". Do you have the exact message that printed when the game crashed?

**Comment by baoliejuan** [comment]
The game didnet crash, rather don't accept any input except ctrl-c and take a lot cpu usage, the last output is 
> The frost doesn't seem to chill Mina Harker!--More--

os I use is arch linux 5.18.7 and game is latest version

**Comment by RikerW** [comment]
Wasn't able to reproduce the error - tried a couple more times, but no dice. It sounds like instead of a crash there's an infinite loop somewhere but I didn't find any testing. Are you running 3.21.3 or 3.21.4? 3.21.3 is the default but it's worth asking. What made you think it was when a monster was wearing both armors, just a guess?

**Comment by baoliejuan** [comment]
It's 3.21.4
I tried to let other monsters pick them up and put on, and same thing happened

**Comment by Chris-plus-alphanumericgibberish** [comment]
Confirmed: any monster wearing both body armor and a shirt will do this.
