### ISSUE TITLE
Several monster spells do not require line of sight

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#2078]
I had aggravate monster for once in my game. On astral I was getting a bunch of lightning bolts bouncing off of me and ice chunks with no line of sight. Earlier in the game, around caillea eladrin without line of sight, pic below was happening. I would guess these spells require monsters to target a valid mux/muy but not check line of sight, and since i had aggravate monster they knew where I was and could cast at me through walls.
![image](https://user-images.githubusercontent.com/8377693/197420802-fb8b3798-b3c3-4406-9777-dba07f98c209.png)

**Comment by NeroOneTrueKing** [comment]
Aha -- directly calling `cast_spell()` bypasses a bunch of checks that are in `spell_would_be_useless()`. In `dostorm()` Chris has recreated _most_ of the necessary conditions but doesn't have a `clear_path()`. I think I will split `spell_would_be_useless()` into more functions so that actual "X should not be castable" is checked in `cast_spell()` too.
