### ISSUE TITLE
Teleporting an MG_RIDER corpse causes impossibles and then a segfault

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#2080]
"bhito: obj is not floor or Stone To Flesh spell. Program in disorder - you should probably S)ave and reload the game." and then a segfault in bhitpile trying to deref otmp->nexthere
Very easy to replicate.
![image](https://user-images.githubusercontent.com/8377693/201692782-d89f651c-65ac-4a34-9902-cc135c357b12.png)

**Comment by NeroOneTrueKing** [comment]
Cannot reproduce with Death, can reproduce with a Priest of an Unknown God. Weird!

**Comment by NeroOneTrueKing** [comment]
Okay -- it's if the rider likes items / can equip items on the square. On reviving, the newly-revived creature picks up and equips items on its square, which is happening _while_ the zap is trying to affect everything on the square. The result is that the zap's loop-over-objects-here gets an out of date object reference, since the corpse picks up what would have been the 'next' object.
