### ISSUE TITLE
xhity merge and player passive attacks interact improperly

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#353]
" The priest of the deep blue sea swings his mace!  The priest of the deep blue sea hits! The priest of the deep blue sea's cold-iron mace sears your flesh! The priest of the deep blue sea misses.  The priest of the deep blue sea casts a spell at you! Severe wounds appear on your body!  The priest of the deep blue sea is suddenly very cold! You kill the priest of the deep blue sea!  The priest of the deep blue sea swings his mace!  The priest of the deep blue sea hits! The priest of the deep blue sea's cold-iron mace sears your flesh! The priest of the deep blue sea misses. The priest of the deep blue sea points at you, then curses. The priest of the deep blue sea is suddenly very cold!"

The priest died but then kept wailing on me?
Additionally, his spells triggered my passive?
Bad things are happening here.

**Comment by NeroOneTrueKing** [comment]
Breaking this down.

**His spells didn't trigger the passive.**
Rather, passives have been changed to happen only once, and at the end of magr's attack chain. Thus, {weapon -> claw -> spell} will proc the yuki-onna's passive once, after the spell is cast. Not a bug, but this may take some getting used to. It should remain this way because the old behaviour (1 passive proc per attack) turned into insane damage for a creature with multiattacks. I distinctly remember being a yuki-onna and killing minotaurs in 1 turn by standing still.

**The priest died and kept attacking.**
Definitely a bug.

**Comment by NeroOneTrueKing** [comment]
Sorry I pressed the wrong button!
