### ISSUE TITLE
Pen of the Void provides no hit messages

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#364]
Both when shooting things with projectiles and with just hitting things, you get no "you hit X" message. Other messages, like stealth attack stuff is still printed. Not sure if this is a result of xhity or some of riker's pen fixes.

**Comment by NeroOneTrueKing** [comment]
This is caused by riker's artifact-hit fixes for the pen. If there are no spirits bound into the pen, that bit of code isn't printing a special hitmessage (buf[0] == '\0') but it's telling the rest of the program that it had printed a message (vis==TRUE) (so then the basic hitmessage isn't printed either).
