### ISSUE TITLE
Elshava shops can have bad-material artifacts in them

### ISSUE THREAD

**Issue by Chris-plus-alphanumericgibberish** [Chris-plus-alphanumericgibberish/dNAO#403]
set_material() may be appropriate here.  There should probably also be a minimal set material that **just** changes the material, weight, and enforces compliance with artifact material rules, but never changes the base item type.

**Comment by NeroOneTrueKing** [comment]
Sigh. The otyp changes for potions/spellbooks/wands are neat as a gimmick, but you're right that maybe they need to be optional. I would be hesitant to completely bypass otyp-modifications, since that catches ridiculousness like "iron leather armor" and "golden silver arrows".

**Comment by NeroOneTrueKing** [comment]
The bug portion of this issue (artifacts changing material) has been fixed in the devel branch. Marking as fixed in dev.

I don't think that the enhancement portion is a good idea. We seem to have enough trouble already  remembering to call functions instead of directly setting variables, and a function that would never change otyp would likely result in the examples I gave above. It would be wiser to check at the caller (ie, don't attempt to re-material potions/wands/books/rings if we don't want the otyp-changing behaviour).
