### ISSUE TITLE
Nerf Godhands' extra holy/unholy effect

### ISSUE THREAD

**Issue by NeroOneTrueKing** [Chris-plus-alphanumericgibberish/dNAO#702]
Gold 1d20 + full Excalibur 3d7 is strong but not overpowered... but unarmed can be twoweaponed, which make Godhands melt demons like crazy. 100+ damage a round crazy.

Reduce its holy/unholy damage to flat amounts, like +7 holy or so.

**Comment by RikerW** [comment]
Preferred solution for me, who just ran a hlf monk with these, would be +7 flat in addition to the 1d20 gold, or maybe 4d7 instead of the 1d20 with no extra bonuses. I quite like the 25 str/dex, so I think that's ok, along with the gold material.

For cursed damage, should probably just be a flat +7 as well, or maybe a +9? Either one is probably fine.
