### ISSUE TITLE
Lightsabers get damage from STR?

### ISSUE THREAD

**Issue by NeroOneTrueKing** [Chris-plus-alphanumericgibberish/dNAO#739]
Is it appropriate that lightsabers deal more damage with high STR?

Tagged as "balance" because of the implication if this behaviour is changed. Not that lightsabers will particularly suffer from not getting +STR damage, but still.

**Comment by Chris-plus-alphanumericgibberish** [comment]
Lightsabers are typically _described_ as not having mass in the blade, but all the choreography assumes that they do (the big wide swings they do would make little sense if you can't add power to the chop that way. Shockingly enough, the choreography basically treats them like wooden dowels ;) ).

Based on how they behave on screen, they should probably *damage* armor like flaying weapons instead of passing through armor like shining weapons.  But, the flaying mechanic doesn't respect body slot at the moment.

**Comment by NeroOneTrueKing** [comment]
Thanks Chris!
