### ISSUE TITLE
Necro shows up bad in asc dumplog

### ISSUE THREAD

**Issue by RikerW** [Chris-plus-alphanumericgibberish/dNAO#808]
```The The Necronomicon (worth 5000 zorkmids and 12500 points)```

**Comment by NeroOneTrueKing** [comment]
Cause: spellbook of secrets is a "unique item" in objects.c. Other than the artifacts based on the spellbook of secrets, unique items aren't expected to be artifacts. 

Things to be aware of if making the spellbook of secrets not unique:
1. The artifact books are currently randomized because they are unique items. When just "The Necronomicon" is specified in .des, the following code intervenes. (make spellbook of secrets -> turn it into a random artifact -> attempt to call it the necronomicon (which fails)). In mkobj.c, in mksobj(), ln 1307-1309:
```c
	/* unique objects may have an associated artifact entry */
	if (objects[otyp].oc_unique && !otmp->oartifact)
	    otmp = mk_artifact(otmp, (aligntyp)A_NONE);
```

2. It will have to be re-specified as non-writable and non-wishable.
