### ISSUE TITLE
Various places in the code check the obj desc list directly rather than using the o_init.c functions

### ISSUE THREAD

**Issue by RikerW** [Chris-plus-alphanumericgibberish/dNAO#840]
Namely, do_wear.c opera cloak checks and steed.c riding boots checks.

**Comment by NeroOneTrueKing** [comment]
Backend cleanup request: in all of the `find_whatever()` functions, keep a `static int foundotyp = 0;` that's set to the correct otyp once it's been found the first time. Then callers can always call the `find_whatever()` function with minimal overhead, instead of creating their own `static int mboots2 = 0;` or whatever.
