### ISSUE TITLE
Adding an attribute to a monster

### ISSUE THREAD

**Issue by Chris-plus-alphanumericgibberish** [Chris-plus-alphanumericgibberish/dNAO#909]
I'm guessing that this:
```
void
give_mintrinsic(mon, intrinsic)
struct monst * mon;
long intrinsic;
{
	//Probably need to add this to the permonst struct as well
	mon->mintrinsics[((intrinsic)-1)/32] |=  (1L<<((intrinsic)-1)%32);
}

```
results in an intrinsic that would be lost if a monster put on and took off a piece of equipment that granted the same intrinsic?

**Comment by NeroOneTrueKing** [comment]
This would *not* interfere with armor, which uses the `mon->mextrinsics[]` array.
However, `set_mon_data()` (in its current incarnation) overwrites `mon->mintrinsics[]`, which means that intrinsics granted by this hypothetical function could be removed on save-load.

It could be tricky to make intrinsics (with no other markers) stick around, because `set_mon_data()` is used for things like:
> Sparky was a fire elemental that thus had intrinsic fire resistance, but Sparky is now a white dragon -- Sparky should not still have intrinsic fire resistance!

Memory is cheap. We could give all monsters a third array of properties, say, `mon->acquired_trinsics[]` (name pending), which would not be as directly referenced as mintrinsics and mextrinsics. `set_mon_data()` would look at acquired[], and give the monster all the intrinsics that it had acquired through other-than-being-its-species methods.

**Comment by NeroOneTrueKing** [comment]
How I imagine this:
```
/* in monst.h */
unsigned long int mintrinsics[LAST_PROP/32+1]; //(old)
unsigned long int mextrinsics[LAST_PROP/32+1]; //(old)
unsigned long int acquired_trinsics[LAST_PROP/32+1]; //(new)
```
And your new function looks like:
```
void
give_mintrinsic(mon, intrinsic)
struct monst * mon;
long intrinsic;
{
	// Do not need to adjust permonst array, this is specific to THIS individual monster
	mon->acquired_trinsics[((intrinsic)-1)/32] |=  (1L<<((intrinsic)-1)%32);
	set_mon_data(mon, mon->mtyp);
}
```
And in `set_mon_data_core()`, we add:
```
int i;
for (i=0; i<(LAST_PROP/32+1); i++)
	mon->mintrinsics[i] |= mon->acquired_trinsics[i];
```

**Comment by Chris-plus-alphanumericgibberish** [comment]
Ok, yeah, that would work
