### ISSUE TITLE
Peaceful monsters don't walk towards grudge targets

### ISSUE THREAD

**Issue by Chris-plus-alphanumericgibberish** [Chris-plus-alphanumericgibberish/dNAO#911]
They will stop and fight grudge targets if they happen to move adjacent.

**Comment by NeroOneTrueKing** [comment]
They do, actually... but not if they're wielding a ranged weapon. When wielding a ranged weapon, they attempt to kite, which turns out disastrously.

First, call mfind_target() and look for enemies to attack at range. If there is one, attack it, using our move.

Otherwise, go through to m_move, and:
- Find closest hostile
- If wielding a ranged weapon (launcher/firearm), try to run away if distmin<4
- Oh no they're too close run away. And that's our move.

Edit: they also have a rather small search radius (5 squares).
