### ISSUE TITLE
The starlight spell results in a 404 beam not found!

### ISSUE THREAD

**Issue by Chris-plus-alphanumericgibberish** [Chris-plus-alphanumericgibberish/dNAO#975]
It used the format of a melee/ray elemental spell, but the ranged form was actually undirected.

Perhaps it should simply *become* a ray spell now. Although, that would be a large nerf if it was able to be reflected :-\

**Comment by NeroOneTrueKing** [comment]
Linked PR does the bare minimum to turn it into a real spell. Does *not* do unreflectibleness (which I think would be best done by setting the dragonbreath flag in elemspell?), or pw-drain or dr-resistance (like melee spell) because I see that zhitm and zhitu are old-style split between vsm and vsu and don't feel like writing *that* right now.
