### ISSUE TITLE
Bug with AT_BKGT in xhity?

### ISSUE THREAD

**Issue by Chris-plus-alphanumericgibberish** [Chris-plus-alphanumericgibberish/dNAO#997]
bad aatyp for xmeleehity (35)  Program in disorder - you should probably S)ave and reload the game.

**Comment by NeroOneTrueKing** [comment]
That should have been caught and subbed out for another aatyp in `getattk()`. I wonder how it made it past.

**Comment by NeroOneTrueKing** [comment]
Found it.
`dogoat_mon()` in allmain.c calls `xmeleehity()` with `AT_BKGT` attacks.
`AT_BKGT` attacks were originally written to have their aatypes replaced in getattk, which isn't happening here.

It does not make sense to do the subout in `xmeleehity()`, because the subout sometimes isn't even a melee attack.

I think the subout needs to be done in `dogoat_mon()`.
